### DISCUSSION TITLE
[Bug report] InfluxDBUploader: Write to InfluxDB failed: java.lang.RuntimeException

### DISCUSSION THREAD

**Discussion by erkexzcx** [NightscoutFoundation/xDrip#2489] [General]
So I am using a TSDB called VictoriaMetrics. It is impressive TSDB which combines features of both - InfluxDB v1 (push model) and Prometheus with exception performance and other very attractive features.

When I try to setup xDrip+ to deliver metrics to TSDB, I constantly get the following error (I confirm that I've entered correct details):
![image](https://user-images.githubusercontent.com/5955795/203379173-6dd704fb-ed32-49e4-b035-66a07ba1fbf4.png)

Before you jump into the conclusion that it's my fault (not influxdb, misconfiguration, etc..), - I am using [Telegraf](https://github.com/influxdata/telegraf) to deliver metrics from my servers to this TSDB. It works without any issues and I've been using this kind of setup in both corporate and personal environments. However, xDrip+ is throwing an exception. 🤷‍♂️ 

Telegraf configuration fragment for metrics delivery - works without any issues:
```toml
[[outputs.influxdb]]
  urls = ["https://example.com/"]
  username = "myuser"
  password = "mypass"
```

VictoriaMetrics docker container - nothing exceptional (no other configuration files):
```yaml
  victoria-metrics:
    image: victoriametrics/victoria-metrics
    container_name: victoria-metrics
    volumes:
      - /storage/victoria-metrics-data:/victoria-metrics-data
    restart: unless-stopped
```

Caddy (reverse proxy that adds TLS as well as basic HTTP auth) - works fine with Telegraf:
```
example.com {
    reverse_proxy victoria-metrics:8428
    basicauth * {
        myuser XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    }
    encode * zstd gzip
}
```

I literally have zero clue of what might cause this behavior, but it is clear to me - there is a bug somewhere in the app. It should work fine, but it does not.

Please contact me via erikmnkl@gmail.com (prior let me know your email here from which you will be contacting) so I can setup a playground instance for you using the same configuration.

I guess I should tag @pimeys as [you've been mentioned as an author](https://github.com/NightscoutFoundation/xDrip/issues/184#issuecomment-331903227) of this integration. :) 

EDIT: Looks like this is part that is failing: https://github.com/NightscoutFoundation/xDrip/blob/master/app/src/main/java/com/eveningoutpost/dexdrip/InfluxDB/InfluxDBUploader.java#L116
